"""empty message

Revision ID: 7c46d7c7bfed
Revises: 99a6429f4a67
Create Date: 2024-03-28 13:25:42.369740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c46d7c7bfed'
down_revision: Union[str, None] = '99a6429f4a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'otp_expiry')
    # ### end Alembic commands ###
