"""empty message

Revision ID: 99a6429f4a67
Revises: e01fee7d0892
Create Date: 2024-03-26 16:47:44.765135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a6429f4a67'
down_revision: Union[str, None] = 'e01fee7d0892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Leader', sa.String(), nullable=False),
    sa.Column('Name_of_Voter', sa.String(), nullable=False),
    sa.Column('Reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Voting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Voting',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Voting_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Leader', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name_of_Voter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='Voting_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Voting_pkey')
    )
    op.drop_table('vote')
    # ### end Alembic commands ###
