"""Remove otp_expiry column

Revision ID: f1088a37793e
Revises: 7c46d7c7bfed
Create Date: 2024-03-28 13:45:53.603600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1088a37793e'
down_revision: Union[str, None] = '7c46d7c7bfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
